### ISSUE TITLE
Error: call to 'byteswap' is ambiguous (groestl_provider.hpp line 124)

### ISSUE THREAD

**Issue by brev** [kerukuro/digestpp#1]
Hi @kerukuro,

I'm getting a single error when trying to use `digestpp`:

```
algorithm/detail/groestl_provider.hpp:124:26: error:
      call to 'byteswap' is ambiguous
                h[hs > 256 ? 15 : 7] = byteswap(hash_size());
                                       ^~~~~~~~
```

It seems to be getting confused between `uint(16/32/64)_t` types.

If I comment out the #include for `groestl_provider.hpp`, everything works great.

Any ideas?  Thanks much.

**Comment by marcizhu** [comment]
Same issue here. If I comment out the `#include groestl_provider.hpp` I can't compile the tests. Any suggestions?

**Comment by brev** [comment]
@marcizhu I've been able to get around this by only including the hashing algorithms I want. For example, if I only want `sha3/shake256`:

Instead of this (which errors out):
```cpp
#include <digestpp.hpp>
```

I can do this, successfully:
```cpp
#include <hasher.hpp>
#include <algorithm/sha3.hpp>
#include <algorithm/shake.hpp>
```

In case it helps. :)

**Comment by marcizhu** [comment]
It does help a lot!
Anyway, I'll try to fix this issue in the next few days and if I succeed I'll make a PR.

**Comment by marcizhu** [comment]
I found out that adding a cast on file [groestl_provider.hpp:124](https://github.com/kerukuro/digestpp/blob/master/algorithm/detail/groestl_provider.hpp#L124) fixes this error. The trick is to change this:
```cpp
h[hs > 256 ? 15 : 7] = byteswap(hash_size());
```
To this:
```cpp
h[hs > 256 ? 15 : 7] = byteswap((uint64_t)hash_size());
```

Note that this only works if `size_t` is 8 bytes long, just as `uint64_t` is (which is the case for all 64-bit systems, but might not work on 32-bit).

Alternatively, removing [the groestl.hpp include](https://github.com/kerukuro/digestpp/blob/92dc9b33a63da76b088ac2471fbb350177d04c2f/digestpp.hpp#L12) from `digestpp.hpp` also fixes this, but you won't be able to use this hash function. Kind of similar to @brev's solution.

**Comment by marcizhu** [comment]
I tried compiling this library on Windows, Linux and macOS and it looks like a mac-only issue. MSVC (on Windows) and both Clang and GCC do not raise any errors, only Clang on macOS gives this error. I've fixed it in my fork at [marcizhu/digestpp](https://github.com/marcizhu/digestpp), use it if you have this issue. I'll make a pull request soon
