### ISSUE TITLE
Groestl/* test passed with errors with 32bit compilation

### ISSUE THREAD

**Issue by MicSm** [kerukuro/digestpp#13]
Platform and compiler:
***
Windows 7 x64 [Version 6.1.7601]
Microsoft Visual Studio Community 2017 Version 15.9.26
VisualStudio.15.Release/15.9.26+28307.1234
Visual C++ 2017   00369-60000-00001-AA395
***

Compiling test.cc with VS2017 using x86 debug/release:
***
Groestl/256 error: expected 8c7ad62eb26a21297bc39c2d7293b4bd4d3399fa8afab29e970471739e28b301, actual b70d81f0215c295a43193b0439d688d852f417a186f173bededd5a5d71c5f17b
Groestl/512 error: expected badc1f70ccd69e0cf3760c3f93884289da84ec13c70b3d12a53a7a8a4a513f99715d46288f55e1dbf926e6d084a0538e4eebfc91cf2b21452921ccde9131718d, actual 545f354922267ece6b14fa129074058acd34b3314d65b30be3d29a64d92355ee2dee2086dfc9028e0c2aa455fd05e18b3544697b522533a5640ac40c9766d258
Self-test completed with 2 errors.
***

Compiling test.cc with VS2017 using x64 debug/release, execution passes witout any error.

g++ x64 compilation and execution also passed without any error.

**Comment by kerukuro** [comment]
Thank you for the report! The issue has now been fixed.
